name: vvl.me

on:
  push:
    branches:
      master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: npx hexo generate

      - name: deploy
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p ~/.ssh
          cat > ~/.ssh/id_ed25519 << EOF
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          chmod 0400 ~/.ssh/id_ed25519
          # ignore host fingerprint
          cat > ~/.ssh/config << EOF
          StrictHostKeyChecking no
          EOF
          rsync -avz public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_DEST }}
